doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        charset: utf8
        default_table_options:
            charset: utf8
            collate: utf8_general_ci
        server_version: mariadb-10.3.16
        types:
            datetime_immutable: \Carbon\Doctrine\DateTimeImmutableType
            datetime: \Carbon\Doctrine\DateTimeType
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Infrastructure/Driven/Persistence/Doctrine/Mapping'
                prefix: 'App\Domain'
                alias: App