doctrine:
  dbal:
    types:
      uuid: 'Ramsey\Uuid\Doctrine\UuidType'
      appId: 'App\Infrastructure\Driven\DatabaseIdentifier\Doctrine\AppIdType'
      appCategoryId: 'App\Infrastructure\Driven\DatabaseIdentifier\Doctrine\AppCategoryIdType'