version: '3.7'

services:
    php:
        container_name: appurse_clone_ddd_php
        volumes:
            - '..:/opt/app'
        build:
            context: ../
            dockerfile: docker/services/php/php.Dockerfile

    nginx:
        container_name: appurse_clone_ddd_nginx
        build:
            context: ../
            dockerfile: docker/services/nginx/nginx.Dockerfile
        volumes:
            - '..:/opt/app'
        ports:
            - "8129:80"

    db:
        container_name: appurse_clone_ddd_db
        hostname: "appurse-clone"
        ports:
            - 3307:3306
